### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by derek3x** [wlan222/kisscartoon#1]
./kisscartoon.sh http://kisscartoon.me/Cartoon/Aqua-Teen-Hunger-Force-Season-10
\033[1;33m[19:57:25]\033[0m\033[0;32m Spidermonkey seems to be installed\033[0m
\033[1;33m[19:57:25]\033[0m\033[0;32m xclip seems to be installed\033[0m
\033[1;33m[19:57:26]\033[0m Getting Link for\033[0;32m http://\033[0m
unwrap.js:108: ReferenceError: readFile is not defined
\033[1;33m[19:57:26]\033[0m The Download Links are in \033[0;32mlinks.txt\033[0m
./kisscartoon.sh: line 38: [: =: unary operator expected

**Comment by jafrewa** [comment]
They recently added Cloudflare Anti-Bot Protection to their Page. I had to rewrite the Script in Python. Im gonna commit that one ASAP.

**Comment by derek3x** [comment]
Thanks

**Comment by jafrewa** [comment]
Alright i updated the Repo. If you have any further Questions feel free to ask.

**Comment by derek3x** [comment]
I appreciate the fast turn around.  Nice work.

To make it work on Linux(or my machine), I changed these lines:

```python
def download(url, name, quiet = False):
    dest = "./Downloads/"
    path = "%s%s" % (dest, name)
    if os.path.isfile(path):
        if not quiet:
            print "Skipping %s" % name
        return
    else:
        obj = SmartDL(url, "%s%s" % (dest, name))
        obj.start()
```

Seems to work.  I really did not do a very in depth check.  Thanks again.
