### ISSUE TITLE
No Episode links found...

### ISSUE THREAD

**Issue by jvonhoff** [wlan222/kisscartoon#10]
Hey, great little app here!

I'm having a couple of issues though, and I think KC is the cause.  Possibly the "Are you human" captcha.

When I call kissgrab.py with -l or -d, I'm always getting "No Episode links found for [some episode page]".  It's not usually the FIRST episode on the page, but 3-4 into the series, and it never writes out the links.txt or html for downloading the ones that DO work.  Would it be possible to write out the successful links, and then I can just get the missing ones manually?

**Comment by jafrewa** [comment]
Can i close this as of #12 ?

**Comment by jvonhoff** [comment]
I think so.  We'll still get captchas, but the kissgrab.dat file will still give you successful links & will allow you to re-run to get missing links at a later time, which is likely the best we can get without a captcha solver.

**Comment by jafrewa** [comment]
A captcha solver might be a tad bit overkill since if you pay something you might as well pay kisscartoon.
