### ISSUE TITLE
Sample seems to fail

### ISSUE THREAD

**Issue by bytepoet** [wlan222/kisscartoon#16]
The following example provides a links.txt file.  Am i doing something wrong?
`python kissgrab.py -s http://kisscartoon.me/Cartoon/Aqua-Teen-Hunger-Force-Season-10`

The capthanewnewnewnewnewnewnew causes me a little concern.  
`https://2.bp.blogspot.com/BYa6R3DM3CcpX8wpHMITJLSjiwbcZvqLOmGCzDNgkWunIA_Z-hD3oa7q3Aoi732lXhIP-gzo=m22captchanewnewnewnewnewnewnewnew`

**Comment by jafrewa** [comment]
You hit the rate limit if I interpret this correctly. We're currently
working on adding ways to avoid this.

**Comment by bytepoet** [comment]
understood.  Just to be clear, this was executed on a virtual machine from a cloud provider as well as my home machine.  If there's any more information you'd like from my tests, please define your request.

**Comment by jafrewa** [comment]
All you can do at the moment is add a higher time to wait between requests

Am 15.10.2016 10:44 vorm. schrieb "Byte" <notifications@github.com>:

**Comment by barryanders** [comment]
Same issue.

**Comment by barryanders** [comment]
Thanks, it's working now. Awesome!
