### ISSUE TITLE
[ERROR] PRINT

### ISSUE THREAD

**Issue by GoNotCougsWA** [wlan222/kisscartoon#19]
I got a ERROR 

  File "kissgrab.py", line 186
    print val
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by jvonhoff** [comment]
Make sure you're using python 2, not python 3.  The requirement for print having parentheses is from python 3, I believe.

**Comment by GoNotCougsWA** [comment]
Ok, Now it is running but now I am not getting any info or messages

**Comment by jvonhoff** [comment]
This is likely due to the same issue discussed in #18 so I recommend closing this.

**Comment by GoNotCougsWA** [comment]
Ok
