### ISSUE TITLE
Error on pulling links

### ISSUE THREAD

**Issue by JorgeDel** [wlan222/kisscartoon#3]
This is the error I get when running the script to download links - sudo python kisscartoon.py -l -s [link]
It occurs about halfway through the list

Traceback (most recent call last):
  File "kisscartoon.py", line 85, in <module>
    qualitys = get_episode(episode, args.quiet, args.low_quality)
  File "kisscartoon.py", line 43, in get_episode
    print("Quality : " + quali[0])
IndexError: list index out of range

**Comment by jafrewa** [comment]
Can you give me the link you're trying to access ?

**Comment by JorgeDel** [comment]
http://kisscartoon.me/Cartoon/Bobby-s-World

**Comment by jafrewa** [comment]
I can reproduce it now. We're triggering a CAPTCHA on Kisscartoon :(

**Comment by JorgeDel** [comment]
I used it to download and go through season 4 ep 1 before it seemed to trigger an error. I will retry tonight though maybe add in the delay for the links. Thank you! Will let you know how it turns out

**Comment by JorgeDel** [comment]
it occured again during download this time jsut fyi

**Comment by jafrewa** [comment]
Unfortunately I can't really do anything besides adding a delay

**Comment by jafrewa** [comment]
And it would be a delay like 5 minutes so we dont trigger the captcha
