### ISSUE TITLE
Error on Decoding URL of selectQuality

### ISSUE THREAD

**Issue by hakchul77** [wlan222/kisscartoon#4]
Hi, 

Is it still working?
It returns "ValueError: unknown url type: t%A2v%B3%BA%83%1D%ABB%04"
And I got strange character set when I execute this part "base64.b64decode(src.get('value'))".

Thanks,

**Comment by jafrewa** [comment]
Gonna look into this when I get home. Kisscartoon/Anime is actively
preventing scripts like this so I'm not sure just how fixable this is.
Am 20.04.2016 5:04 nachm. schrieb "hakchul77" <notifications@github.com>:

**Comment by slipsystem** [comment]
I can confirm. I am getting the same error. I am not a python coder but I think it has something to do with this line 

dlinks.append(base64.b64decode(src.get('value')))

**Comment by slipsystem** [comment]
thanks for the awesome work by the way.

**Comment by jafrewa** [comment]
Ugh they changed their Link "Encryption"

**Comment by hakchul77** [comment]
I think so.
I learned a lot from your code.
Thanks anyway.

**Comment by wlan222** [comment]
I found out that they use aes encryption with a pbkdf2 key on the clientside to hide the link. I'm not that great with Javascript and so I'm porting it to python

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 21. Apr. 2016 um 1:27 hat hakchul77<notifications@github.com> Folgendes geschrieben:   
I think so.
I learned a lot from your code.
Thanks anyway.

**Comment by jafrewa** [comment]
Okay i fixed and pushed a build. You now also require pyCrypto to decrypt the links.
