### ISSUE TITLE
Error decrypting

### ISSUE THREAD

**Issue by franzene2334** [wlan222/kisscartoon#6]
Hey so I ran into this issue not sure if its known or not 

C:\Python27>python C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-m
aster\kisscartoon.py http://kisscartoon.me/Cartoon/Thundercats-1985
Serie : Thundercats-1985
Episode : Season-01-Episode-001.mp4
Traceback (most recent call last):
  File "C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-master\kissc
artoon.py", line 131, in <module>
    qualitys = get_episode(episode, args.quiet, args.low_quality)
  File "C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-master\kissc
artoon.py", line 84, in get_episode
    dlinks.append(decoder.decrypt(src.get('value')))
  File "C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-master\kissc
artoon.py", line 27, in decrypt
    val = 'https://redirect%s' % val[val.index('or.googlevideo.com'):]
ValueError: substring not found

**Comment by wlan222** [comment]
Yeah I used a pretty messed up workaround for that

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 28. Apr. 2016 um 2:00 hat franzene2334<notifications@github.com> Folgendes geschrieben:   
Hey so I ran into this issue not sure if its known or not 

C:\Python27>python C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-m
aster\kisscartoon.py http://kisscartoon.me/Cartoon/Thundercats-1985
Serie : Thundercats-1985
Episode : Season-01-Episode-001.mp4
Traceback (most recent call last):
 File "C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-master\kissc
artoon.py", line 131, in 
 qualitys = get_episode(episode, args.quiet, args.low_quality)
 File "C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-master\kissc
artoon.py", line 84, in get_episode
 dlinks.append(decoder.decrypt(src.get('value')))
 File "C:\Users\franzene\Downloads\Thundercats\Season1\kisscartoon-master\kissc
artoon.py", line 27, in decrypt
 val = 'https://redirect%s' % val[val.index('or.googlevideo.com'):]
ValueError: substring not found

**Comment by jafrewa** [comment]
Okay found the bug. Fixing some internal stuff. Expect a fix tomorrow.

**Comment by jafrewa** [comment]
Done.
