### ISSUE TITLE
Script does nothing, just exits on being run.

### ISSUE THREAD

**Issue by rochakgupta** [wlan222/kisscartoon#8]
When I tried to download from KissAnime using the command
`python kissgrab.py http://kissanime.to/Anime/Garo-Honoo-no-Kokuin`
the script just exits without doing anything. No errors, nothing is thrown.

**Comment by jafrewa** [comment]
Known issue. The Encryption for the sites changed. While im fixing this you can try using https://github.com/Twoure/KissNetwork.bundle which is supposedly working

**Comment by jafrewa** [comment]
Fixed #9
